# Generated by Django 6.0.5 on 2026-06-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
