# Generated by Django 6.0.5 on 2026-06-23 16:38

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_delete_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism Familiya')),
                ('position', models.CharField(choices=[('editor_in_chief', 'Bosh muharrir'), ('deputy_editor', "O'rinbosar muharrir"), ('editor', 'Muharrir'), ('reviewer', 'Taqrizchi'), ('secretary', 'Kotib'), ('member', "A'zo")], default='member', max_length=30, verbose_name='Lavozim')),
                ('workplace', models.CharField(max_length=255, verbose_name='Ish joyi')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yoshi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=journal.models.staff_photo_path, verbose_name='Rasmi')),
                ('bio', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatish")),
            ],
            options={
                'verbose_name': "Jurnal a'zosi",
                'verbose_name_plural': "Jurnal a'zolari",
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
