# Generated by Django 6.0.5 on 2026-06-24 08:15

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.user_avatar_path, verbose_name='Profil rasmi'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name="O'zim haqimda"),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam'),
        ),
    ]
