# Generated by Django 6.0.5 on 2026-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_user_avatar_user_bio_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
            ],
            options={
                'verbose_name': 'Tashrif',
                'verbose_name_plural': 'Tashriflar',
                'unique_together': {('date', 'ip_address')},
            },
        ),
    ]
