# Generated by Django 6.0.5 on 2026-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('date', models.DateField(verbose_name='Sana')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Joyi')),
                ('url', models.URLField(blank=True, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Konferensiya',
                'verbose_name_plural': 'Konferensiyalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nomi')),
                ('category', models.CharField(choices=[('normative', "Me'yoriy hujjat"), ('requirement', 'Maqola talablari'), ('template', 'Shablon'), ('other', 'Boshqa')], default='normative', max_length=15, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fayl')),
                ('url', models.URLField(blank=True, verbose_name='Tashqi havola')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatish")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
