# Generated by Django 6.0.5 on 2026-06-28 16:28

import django.db.models.deletion
import journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_conference_document_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod (masalan: 18.00.00)')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=500, verbose_name="Mualliflar (to'liq ro'yxat)"),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='Maqola matni (HTML)'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Chop etilgan sana'),
        ),
        migrations.AddField(
            model_name='article',
            name='template_pdf',
            field=models.FileField(blank=True, null=True, upload_to=journal.models.article_template_pdf_path, verbose_name='Shablon PDF (tahririyat tomonidan)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Muallif (foydalanuvchi)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(upload_to=journal.models.article_upload_path, verbose_name='PDF Fayl (muallif tomonidan yuborilgan)'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.articlecategory', verbose_name="Yo'nalish / Kategoriya"),
        ),
    ]
