# Generated by Django 6.0.5 on 2026-06-28 18:04

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_articlecategory_article_authors_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=journal.models.article_upload_path, verbose_name='Fayl (PDF yoki Word .docx)'),
        ),
    ]
