# Generated by Django 6.0.5 on 2026-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_article_file_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('submitted', 'Yangi maqola'), ('initial_review', 'Dastlabki tekshiruv'), ('under_review', 'Taqriz jarayonida'), ('returned', 'Tuzatish uchun qaytarilgan'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('ready_to_publish', 'Nashrga tayyor'), ('published', 'Nashr etilgan')], default='submitted', max_length=20, verbose_name='Maqola holati'),
        ),
    ]
