# Generated by Django 6.0.5 on 2026-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default="O'zbekiston", max_length=100, null=True, verbose_name='Davlat'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
    ]
