# Generated by Django 6.0.5 on 2026-07-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_user_country_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Jild muqovasi (rasmi)'),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Davri (Masalan: 1-chorak, Yanvar-Mart)'),
        ),
    ]
