# Generated by Django 6.0.5 on 2026-07-31 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_journalissue_cover_image_journalissue_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Tugash sahifasi (To'plamda)"),
        ),
        migrations.AddField(
            model_name='article',
            name='start_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Boshlanish sahifasi (To'plamda)"),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='full_pdf',
            field=models.FileField(blank=True, null=True, upload_to='issues_pdf/', verbose_name="To'liq to'plam (PDF)"),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.articlecategory', verbose_name="Yo'nalish"),
        ),
    ]
