# Generated by Django 6.0.5 on 2026-08-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_article_end_page_article_start_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='editorial_doc',
            field=models.FileField(blank=True, help_text="Word (.docx) fayl. Nashr boshidagi muqova va tahririyat a'zolari sahifasi uchun.", null=True, upload_to='issues_docs/', verbose_name='Muqova va Tahririyat Word hujjati (.docx)'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Nashr muqovasi (rasmi)'),
        ),
    ]
