# Generated by Django 6.0.5 on 2026-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_journalissue_editorial_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='conferences/pdfs/', verbose_name='Axborot xati / Fayl (PDF)'),
        ),
    ]
