# Generated by Django 6.0.5 on 2026-09-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_conference_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='back_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Orqa muqovasi (rasmi)'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Oldi muqovasi (rasmi)'),
        ),
    ]
