# Generated by Django 5.2.16 on 2026-09-08 03:29

import django.db.models.deletion
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_journalissue_back_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video fayl (MP4/WebM)'), ('video_url', 'Video havola (YouTube/Vimeo/Web URL)')], default='image', max_length=20, verbose_name='Media turi')),
                ('file', models.FileField(blank=True, null=True, upload_to=journal.models.news_media_path, verbose_name='Fayl (Rasm yoki Video)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo/MP4 havolasi)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Izoh / Sarlavha')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='journal.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik media fayli',
                'verbose_name_plural': 'Yangilik media fayllari (Rasmlar va Videolar)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
