# Generated by Django 6.0.5 on 2026-09-08 11:43

import django.db.models.deletion
import journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_journalissue_back_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='Taqrizchi izohi / Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taqriz qilingan sana'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL, verbose_name='Taqrizchi / Muharrir'),
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video fayl (MP4/WebM)'), ('video_url', 'Video havola (YouTube/Vimeo/Web URL)')], default='image', max_length=20, verbose_name='Media turi')),
                ('file', models.FileField(blank=True, null=True, upload_to=journal.models.news_media_path, verbose_name='Fayl (Rasm yoki Video)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo/MP4 havolasi)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Izoh / Sarlavha')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='journal.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik media fayli',
                'verbose_name_plural': 'Yangilik media fayllari (Rasmlar va Videolar)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
