# Generated by Django 6.0.5 on 2026-09-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_alter_article_id_alter_articlecategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='Taqrizchi izohi / Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taqriz qilingan sana'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL, verbose_name='Taqrizchi / Muharrir'),
        ),
    ]
