# Generated by Django on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_article_review_notes_article_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='icon',
            field=models.CharField(
                blank=True,
                default='',
                help_text="FontAwesome ikona klasi (bo'sh bo'lsa avtomatik mos ikona tanlanadi)",
                max_length=50,
                verbose_name='Ikona klasi (masalan: fa-building)'
            ),
        ),
    ]
