# Generated by Django on 2026-09-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_articlecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='assigned_reviewer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_articles',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Biriktirilgan taqrizchi'
            ),
        ),
    ]
