# Generated by Django 6.1.1 on 2026-09-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_article_assigned_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract_en',
            field=models.TextField(null=True, verbose_name='Annotatsiya / Abstract'),
        ),
        migrations.AddField(
            model_name='article',
            name='abstract_ru',
            field=models.TextField(null=True, verbose_name='Annotatsiya / Abstract'),
        ),
        migrations.AddField(
            model_name='article',
            name='abstract_uz',
            field=models.TextField(null=True, verbose_name='Annotatsiya / Abstract'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name="Kalit so'zlar (vergul bilan ajrating)"),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="Kalit so'zlar (vergul bilan ajrating)"),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="Kalit so'zlar (vergul bilan ajrating)"),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='conference',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='conference',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='conference',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ism Familiya'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ism Familiya'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ism Familiya'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position_en',
            field=models.CharField(choices=[('editor_in_chief', 'Bosh muharrir'), ('deputy_editor', "O'rinbosar muharrir"), ('editor', 'Muharrir'), ('reviewer', 'Taqrizchi'), ('secretary', 'Kotib'), ('member', "A'zo")], default='member', max_length=30, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position_ru',
            field=models.CharField(choices=[('editor_in_chief', 'Bosh muharrir'), ('deputy_editor', "O'rinbosar muharrir"), ('editor', 'Muharrir'), ('reviewer', 'Taqrizchi'), ('secretary', 'Kotib'), ('member', "A'zo")], default='member', max_length=30, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position_uz',
            field=models.CharField(choices=[('editor_in_chief', 'Bosh muharrir'), ('deputy_editor', "O'rinbosar muharrir"), ('editor', 'Muharrir'), ('reviewer', 'Taqrizchi'), ('secretary', 'Kotib'), ('member', "A'zo")], default='member', max_length=30, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='workplace_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ish joyi'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='workplace_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ish joyi'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='workplace_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ish joyi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
