# Generated by Django 6.1.1 on 2026-10-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_article_abstract_en_article_abstract_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Jurnal nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug (masalan: arxitektura)')),
                ('description', models.TextField(blank=True, verbose_name='Jurnal haqida (qisqacha)')),
                ('issn', models.CharField(blank=True, max_length=50, verbose_name='ISSN raqami')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journals/', verbose_name='Muqova rasmi')),
                ('founded_year', models.PositiveIntegerField(default=2024, verbose_name='Tashkil etilgan yili')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnallar',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_set', to='journal.journal', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='journal.journal', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='conference',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='journal.journal', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='document',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='journal.journal', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journal.journal', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='news',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='journal.journal', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='journal.journal', verbose_name='Jurnal'),
        ),
    ]
