# Generated by Django 6.1.1 on 2026-10-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_journal_article_journal_articlecategory_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Jurnal haqida (qisqacha)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Jurnal haqida (qisqacha)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Jurnal haqida (qisqacha)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Jurnal nomi'),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Jurnal nomi'),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Jurnal nomi'),
        ),
    ]
